### ISSUE TITLE
ARM Template Conditions (Invalid Template)

### ISSUE THREAD

**Issue by gtewksbury** [rjmax/Build2017#1]
Are conditions currently supported in any Azure regions?  When i try to run the neworexisting conditional example in EastUS or EastUS2, I receive the following validation error (i noticed you deployed yours to eastus2eaup):

10:21:18 - 10:21:17 AM - Error: Code=InvalidRequestContent; Message=The request content was invalid and could not be deserialized: 'Could not find member 'condition' on object of type 'TemplateResource'. Path 'properties.template.resources[0].condition', line 78, position 23.'.
10:21:18 - The deployment validation failed

**Comment by adamreeve** [comment]
I get a slightly different error when deploying my own template through PowerShell and am also trying to find out what the story is with support for the condition property:

```
New-AzureRmResourceGroupDeployment : 18:47:39 - Error: Code=InvalidTemplate;
Message=Deployment template validation failed: 
'The template resource '[concat(variables('web_app_name'), '/Dynatrace')]'
at line '223' and column '10' uses condition property which is not supported yet.'.
```

It sounds like it's not supported, but it's in the documentation at https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-authoring-templates

**Comment by ljtill** [comment]
+1 - I've tested this template with East US and East US 2 with no luck.

**Comment by adamreeve** [comment]
It looks like this is being rolled out to other regions, it now works for me in West Europe.

**Comment by gtewksbury** [comment]
It looks like this has been rolled out to East US (the example template worked for me)
