### ISSUE TITLE
copyIndex for datadisks not working?

### ISSUE THREAD

**Issue by aoby01** [rjmax/Build2017#2]
Hi,

following https://azure.microsoft.com/en-gb/resources/videos/build-2017-azure-resource-manager-templates-life-after-first-deployment/ i was drawn here and tried the mechanism used in https://github.com/rjmax/Build2017/blob/master/Act1.TemplateEnhancements/Chapter02.PropertyCopies.json using copy to extend the storage-profile datadisks.

This however does not seem to work out for me:
statusCode:BadRequest statusMessage:{"error":{"code":"InvalidTemplate","message":"Unable to process template language expressions for resource 'XXX' at line '1' and column '2360'. 'The template function 'copyIndex' is not expected at this location. The function can only be used in a resource with copy specified. Please see https://aka.ms/arm-copy for usage details.'"}}

  "copy": [
                      {
                        "name": "dataDisks",
                        "count": "3",
                        "input": {
                          "diskSizeGB": "1000",
                          "lun": "[copyIndex('dataDisks')]",
                          "createOption": "Empty"
                        }
                      }
                    ]

I set the api versions according to the one in the templates and i am running this in westeurope region.
Is there anything else needed to get this running?

Thanks and cheers

**Comment by rjmax** [comment]
There was a regression the week after //build; this should be working now :)

**Comment by aoby01** [comment]
Thanks - i retried and i can confirm that it works now.
